exchange_config:
  bonding_curve_config:
    curve_type: exponential
    curve_params:
      y0: 0
      x0: 0
      m: 0.0025
      n: 2
  wealth_config:
    supply: 10
    reserve: 10
  tax_config:
    tax_amount: 0.02
    tax_type: relative
model_config:
  max_steps: 3650
  agents:
    - agent_config:
        wealth_config:
          supply: 0
          reserve: 100
      curve_config:
        curve_type: exponential
        curve_params:
          m: 0.0000388121
          n: 2.2766242792778003144078262567225973491484920946499536355393339790
          y0: 10
  creator:
    wealth_config:
      supply: 10
      reserve: 0
    curve_config:
      curve_type: logistic
      curve_params:
        a: 19.62153284167117
        k: 513.4793145897387
        c: 0.28089581922142964
        q: 0.3459871425861641
        b: -0.04108712657497574
        m: 1160.4354435463893
        v: 0.4201762094399637
